## Playbook: Install Tailscale on Debian
---
- name: === Install Tailscale on Debian
  hosts: all
  # ref: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html
  # ref: https://docs.ansible.com/ansible/latest/plugins/become.html#become-plugins
  become: true
  become_user: root
  tasks:
  - include_vars: main.yaml
  - name: Install Tailscale on Debian
    # ref: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_role_module.html
    include_role:
      name: fn_tailscale
      # ref: https://stackoverflow.com/questions/73724567/how-to-have-multiple-tasks-under-one-role-in-ansible
      tasks_from: "install-tailscale-on-debian-{{ ansible_distribution_release }}"
