---
## === PLAY 1/2
- name: === (1/2) Setup Raspberry Pi Bookworm to DNS node - v1
  hosts: all
  # ref: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html
  # ref: https://docs.ansible.com/ansible/latest/plugins/become.html#become-plugins
  become: true
  become_user: root
  # become_method: enable
  # vars:
  #   current_user: "{{ lookup('env', 'USER') }}"
  tasks:

  # ref: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
  - name: Install required packages
    ansible.builtin.apt:
      update_cache: true
      state: latest
      name:
        - ansible
        - aptitude # Install aptitude, which is preferred by Ansible as an alternative to the apt package manager.
        - dnsutils # dig

  # ref: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html
  - name: Setup Docker
    include_role:
      name: fn_docker
      # ref: https://stackoverflow.com/questions/73724567/how-to-have-multiple-tasks-under-one-role-in-ansible
      tasks_from: main # Intentionally defined to remember later - it can be used to include different tasks file in the role.
    vars:
      # ansible_user is special-variable
      # ref: https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html#special-variables
      current_user: "{{ ansible_user }}"

  # ref: https://github.com/fnazz/docker-adguard-unbound-wireguard/blob/main/docker-compose.yml
  # ref: https://docs.ansible.com/ansible/latest/collections/community/docker/docker_network_module.html
  - name: Create Docker network - bridge
    community.docker.docker_network:
      name: private-net
  #     ipam_config:
  #       - subnet: 172.24.27.0/24

  # ref: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
  - name: Git checkout moon-rapi.git
    ansible.builtin.git:
      repo: https://github.com/Gatsby-Lee/moon-rapi.git
      dest: /mnt/moon-rapi
      single_branch: yes
      version: main

  # ref: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
  - name: Create `/mnt/dockers/adguard` if it does not exist
    ansible.builtin.file:
      path: /mnt/dockers/adguard
      state: directory
      mode: '0755'

## === PLAY 2/2
# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04
- name: === (2/2) Start Services on Docker
  hosts: all
  # ref: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html
  # ref: https://docs.ansible.com/ansible/latest/plugins/become.html#become-plugins
  become: true
  become_user: root
  # become_method: enable
  # vars:
  #   current_user: "{{ lookup('env', 'USER') }}"
  tasks:

  - name: Tear down existing services
    community.docker.docker_compose:
      project_src: flask
      state: absent
