---
  - name: Setup Raspberry Pi Bookworm to DNS node - v1
    hosts: all
    # ref: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html
    # ref: https://docs.ansible.com/ansible/latest/plugins/become.html#become-plugins
    become: true
    become_user: root
    become_method: enable
    # vars:
    #   current_user: "{{ lookup('env', 'USER') }}"
    tasks:

    - name: Print a message
      ansible.builtin.debug:
        msg: ">>>>>>>>>> START: playbook - {{ ansible_user }}"

    # ref: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
    - name: Install required packages
      ansible.builtin.apt:
        update_cache: true
        state: latest
        name:
          - ansible
          - aptitude # Install aptitude, which is preferred by Ansible as an alternative to the apt package manager.
          - dnsutils # dig

    # ref: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
    - name: Git checkout moon-rapi.git
      ansible.builtin.git:
        repo: https://github.com/Gatsby-Lee/moon-rapi.git
        dest: /mnt/moon-rapi
        single_branch: yes
        version: main

    # ref: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html
    - name: Role - Setup Docker
      include_role:
        name: fn_docker
      vars:
        # ansible_user is special-variable
        # ref: https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html#special-variables
        current_user: "{{ ansible_user }}"

    - name: Print a message
      ansible.builtin.debug:
        msg: "<<<<<<<<<< END: playbook"
