## !! THIS DOES NOT WORK as EXPECTED.
# The `tasks_from`
## Playbook: Setup Docker Compose
## Steps
#  step 1: execute fn_docker.setup-compose tasks
---
- name: === Setup Docker Compose
  hosts: all
  # ref: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html
  # ref: https://docs.ansible.com/ansible/latest/plugins/become.html#become-plugins
  # become: true
  # become_user: root
  # ref: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html
  ## !! The `tasks_from` does NOT work the way in `include_role`.
  # role always uses fn_docker/tasks/main.yaml
  roles:
    - role: "fn_docker"
      tasks_from: setup-compose
