version: '3.8'

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped
    # network_mode: bridge
    ports:
      - 8123:8123

  reverse_proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    # network_mode: bridge
    ports:
      - "80:80"
      - "443:443"

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16