# ref: https://homarr.dev/docs/introduction/installation#installation-using-docker-compose-or-portainer-stacks
version: '3'
services:
  homarr:
    image: "ghcr.io/ajnart/homarr:latest"
    container_name: homarr
    hostname: "homarr"
    restart: unless-stopped
    ports:
      - 7575:7575
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${PATH_CONFIGS}:/app/data/configs \
      - ${PATH_DATA}:/data \
      - ${PATH_ICONS}:/app/public/icons \
