version: '3'
services:
  adguard:
    image: "adguard/adguardhome:latest"
    container_name: adguard
    hostname: "adguard"
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
      - 53:53/tcp
      - 53:53/udp

    volumes:
      - /mnt/dockers/adguard/work:/opt/adguardhome/work
      - /mnt/dockers/adguard/conf:/opt/adguardhome/conf

networks:
  # docker network create --driver bridge wowbro-dns-net
  # ref: https://docs.docker.com/compose/networking/
  default:
    name: wowbro-dns-net
    external: true
