# --
# Function based Role
# ref: https://docs.ansible.com/ansible/latest/tips_tricks/sample_setup.html#sample-task-and-handler-files-in-a-function-based-role
#
# Role: Setup Tailscale
# ref: https://tailscale.com/download/linux/debian-bookworm
# --

- name: Print a message
  ansible.builtin.debug:
    msg: ">>>>>>>>>> START: setting up Tailscale"

# ref: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
- name: "Download GPG"
  ansible.builtin.get_url:
    # https://tailscale.com/download/linux/debian-bookworm
    url: "https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg"
    dest: "/usr/share/keyrings/tailscale-archive-keyring.gpg"

- name: "Create APT Source list"
  ansible.builtin.get_url:
    # https://tailscale.com/download/linux/debian-bookworm
    url: "https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list"
    dest: "/etc/apt/sources.list.d/tailscale.list"

# Install aptitude, which is preferred by Ansible as an alternative to the apt package manager.
- name: Install aptitude
  apt:
    state: latest
    update_cache: true
    name: aptitude

- name: Install Docker Packages
  apt:
    state: latest
    update_cache: true
    name:
      - tailscale

- name: Print a message
  ansible.builtin.debug:
    msg: "<<<<<<<<<< END: setting up Tailscale | @note: service can be up by `sudo tailscale up` and ip can be found by `tailscale ip -4`"
