# ref: https://jellyfin.org/docs/general/installation/container/
version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${UID}:${GID}
    network_mode: 'host'
    volumes:
      - ${PATH_CONFIG}:/config
      - ${PATH_CACHE}:/cache
      - ${PATH_MEDIA}:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    ## Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # @note: 2023-11-20: well it doesn't look necessary when using network_mode=host
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
