
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

## commented out since missed if custom configuration.yaml is set.
# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml

## how to validate
# ref: https://www.home-assistant.io/common-tasks/container/#configuration-check
## wowbro custom change
# https://www.home-assistant.io/integrations/http/
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.25.0.0/16
