version: '3'
services:
  unbound-dns:
    image: "wowbro/unbound-dns-rpi:1.17.1"
    restart: unless-stopped
    ports:
      - "5335:53/tcp"
      - "5335:53/udp"
    volumes:
      # - ./custom_unbound.sh:/unbound.sh:ro
      - ${PWD}/custom_unbound.sh:/unbound.sh:ro
