version: '3'
services:
  unbound_dns:
    image: "wowbro/unbound-dns-rpi:1.17.1"
    container_name: unbound_dns
    hostname: "unbound"
    restart: unless-stopped
    ports:
      - "5335:53/tcp"
      - "5335:53/udp"
    volumes:
      # - ${PWD}/custom_unbound.sh:/unbound.sh:ro
      # - ${PWD}/root.hints:/opt/unbound/etc/unbound/var/root.hints:ro
      - ./custom_unbound.sh:/unbound.sh:ro
      - ./root.hints:/opt/unbound/etc/unbound/var/root.hints:ro

# networks:
#   # docker network create --driver bridge wowbro-dns-net
#   # ref: https://docs.docker.com/compose/networking/
#   default:
#     name: private-net
#     external: true
