version: '3'
services:
  unbound:
    image: "wowbro/unbound-dns-rpi:1.17.1"
    container_name: unbound
    hostname: "unbound"
    restart: unless-stopped
    ports:
      - "5335:53/tcp"
      - "5335:53/udp"
    volumes:
      # - ./custom_unbound.sh:/unbound.sh:ro
      - ${PWD}/custom_unbound.sh:/unbound.sh:ro
      - ${PWD}/root.hints:/opt/unbound/etc/unbound/var/root.hints:ro
